#!/usr/bin/env python3
'''Module for asynchronously generating and collecting numbers.

This module defines a function that uses an asynchronous generator 
to create a list of 10 random numbers.
'''

from typing import List
from importlib import import_module as using

# Importing async_generator from the previous module
async_generator = using('0-async_generator').async_generator


async def async_comprehension() -> List[float]:
    '''Collects 10 numbers asynchronously from the async_generator.

    This function uses an asynchronous list comprehension to collect 
    10 numbers generated by the `async_generator` coroutine and returns 
    them as a list.

    Returns:
        List[float]: A list containing 10 random floating-point numbers.
    '''
    return [num async for num in async_generator()]
